spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
spring-docs:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
