server:
  port: 8080
  context-path: /api

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
jwt:
  signerKey: ${JWT_SIGNER_KEY}
